### ISSUE TITLE
10주차 : 아이템26

### ISSUE THREAD

**Issue by hmg0616** [hmg0616/Effective-java-study#10]

**Comment by kdh92** [comment]
https://github.com/kdh92/kdh92.github.io/blob/main/Effective%20java/10%EC%A3%BC%EC%B0%A8(%EC%95%84%EC%9D%B4%ED%85%9C%2026).md

**Comment by swiw0721** [comment]
[아이템 26](https://brook-odometer-50c.notion.site/26-86b26cc03ccd45f0b2000b01187c5c99)

**Comment by dingmoong** [comment]
[아이템 26](https://geode-monday-782.notion.site/5-64916755968646aeaf789ce4dd01eed2)

**Comment by hmg0616** [comment]
[26](https://mungyu83.notion.site/26-91829b15434a4f02b5eb61192ffa6400)
