### ISSUE TITLE
14주차 : 아이템 33

### ISSUE THREAD

**Issue by hmg0616** [hmg0616/Effective-java-study#14]

**Comment by dingmoong** [comment]
[지난주 못한 32 & 33](https://geode-monday-782.notion.site/5-64916755968646aeaf789ce4dd01eed2)

**Comment by swiw0721** [comment]
[아이템 33](https://brook-odometer-50c.notion.site/33-6eee875f452e4fe2bec20f8e438c8f4f)

**Comment by hmg0616** [comment]
[아이템 33](https://mungyu83.notion.site/33-8b9a90b03e624b8bbda852199bcc3d82)

**Comment by kdh92** [comment]
<a href="https://github.com/kdh92/kdh92.github.io/blob/main/Effective%20java/14%EC%A3%BC%EC%B0%A8(%EC%95%84%EC%9D%B4%ED%85%9C%2033).md">33</a>
