### ISSUE TITLE
9주차 : 아이템25

### ISSUE THREAD

**Issue by hmg0616** [hmg0616/Effective-java-study#9]

**Comment by dingmoong** [comment]
[아이템 25](https://geode-monday-782.notion.site/4-7561ffe501c84cd8a632f000296d2ab9)

**Comment by swiw0721** [comment]
[아이템 25](https://brook-odometer-50c.notion.site/25-f55b0d390e034f9b8c455c8552866ec0)

**Comment by hmg0616** [comment]
[25](https://mungyu83.notion.site/25-533bdf4b4c7749f585798eb07e723857)

**Comment by kdh92** [comment]
<a href="https://github.com/kdh92/kdh92.github.io/blob/main/Effective%20java/9%EC%A3%BC%EC%B0%A8(%EC%95%84%EC%9D%B4%ED%85%9C%2025).md">아이템 25</a>
